### ISSUE TITLE
create campaign webpage for Obama open policy letter

### ISSUE THREAD

**Issue by tvol** [creativecommons/voice-in-copyright-policy#27]
@mattl do we have (or can you create) a template campaign page that we can use for the Trilogy work? @rebeccalendl and I have created some draft copy here https://docs.google.com/document/d/1imXZ-USyWo0KjKBRWyENl9CTmOjA4zw7_jLrEXFPzT0/edit?usp=sharing

**Comment by tvol** [comment]
cc @ryanmerkley

**Comment by rebeccakross** [comment]
@mattl should we assign Rob to this if it needs to happen by Monday?

**Comment by mattl** [comment]
Rob for the sign up: Make a new group in CiviCRM, make sure it's set as a 'Mailing list' -- then in the Administration menu, go to Profiles... make a new profile, with an email address field, and add people to the group when they fill in it. Set it to update their existing profile (important) and you'll get an HTML snippet you can paste into a page. It's mostly ghastly, so look at https://creativecommons.org/mobile-signup/ for the important parts of the code and duplicate that, or maybe just make the page part of the profile, and we'll link people directly to CiviCRM (this will be a lot easier, save you a lot of headaches with a tight deadline on this)

**Comment by mattl** [comment]
So I went ahead and made a group and a profile for you.

https://donate.creativecommons.org/civicrm/admin/uf/group/update?action=update&id=42&context=group

You'll need to replace my COPY GOES HERE with real copy from @tvol's document, but you should be basically good to go :)

**Comment by rheaplex** [comment]
Thank you @mattl

**Comment by rheaplex** [comment]
@tvol Where does this need to be put when done? I have a preview on civicrm.

**Comment by rheaplex** [comment]
Preview - https://donate.creativecommons.org/civicrm/admin/uf/group?action=preview&id=43&field=0&context=group

**Comment by rebeccakross** [comment]
Do we need separate first and last name fields to synch with civi or will
this do it? All else looks good to me, just waiting on final copy from
Trilogy.

**Comment by tvol** [comment]
@robmyers thanks for spinning this up. the text looks good as a placeholder for now. @rebeccalendl, I've got a note out to @ryanmerkley to help us review the language too. @cablegreen and I are a bit worried about claiming this ground for CC without consulting with the broader coalition first.

**Comment by rheaplex** [comment]
Thanks. Let me know if/when any more action is needed.
