### ISSUE TITLE
read ED NPRM and draft submission with cable

### ISSUE THREAD

**Issue by tvol** [creativecommons/voice-in-copyright-policy#34]
https://www.federalregister.gov/articles/2015/11/03/2015-27930/open-licensing-requirement-for-direct-grant-programs

**Comment by tvol** [comment]
https://docs.google.com/document/d/1CmBhg4hH12zhQonREcc7DCyQusL9BRk4hFppVlwlGSo/edit?ts=56390be8

**Comment by tvol** [comment]
hey @cablegreen i provided some feedback on our collective document. should you and i start a response for CC? or should we do it jointly with CC US? what do you think?

**Comment by cablegreen** [comment]
Yes. Will you please start a new gdoc that will be the CC response? And invite CC US to submit with us - or they might want to submit their own. 

Thanks Tim. 

Cable

**Comment by tvol** [comment]
yes, ok.

**Comment by tvol** [comment]
due december 18th

**Comment by tvol** [comment]
https://docs.google.com/document/u/1/d/1QQJDR7Kfv5qSsCGbAOKhy8OlXc-fMIwzHIMok-myEEI/edit?usp=drive_web

**Comment by tvol** [comment]
@cablegreen can you review this once more before we submit next week?

**Comment by cablegreen** [comment]
Will do. 

Cable

**Comment by tvol** [comment]
http://www.regulations.gov/#!documentDetail;D=ED-2015-OS-0105-0001
