### ISSUE TITLE
monday Dec 7 blog post save the link action

### ISSUE THREAD

**Issue by tvol** [creativecommons/voice-in-copyright-policy#43]
coordinate with meghan

**Comment by mattl** [comment]
we probably can't put much on the site like last time. we have a similar thing going up on the 8th for SOTC.

**Comment by tvol** [comment]
@mattl but would this affect what we can put on the blog?

**Comment by mattl** [comment]
nope.

---

Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by tvol** [comment]
@tvol also C4C similiar post for communia
