### ISSUE TITLE
Fair Use Week activities

### ISSUE THREAD

**Issue by tvol** [creativecommons/voice-in-copyright-policy#51]

**Comment by tvol** [comment]
ideas for fair use week 2016

european copyright consultation
communia
copyright untangled

what did we do last year? 
sarah's post https://creativecommons.org/weblog/entry/44945/ 
tvol's copyright week post on limits of copyright tdm - https://creativecommons.org/weblog/page/11/

what things intersect with CC and fair use in 2015? 

copyright office ECL comments
https://creativecommons.org/weblog/entry/46226/

TPP in relation to limitations and exceptions
https://creativecommons.org/weblog/entry/46455/

dancing baby and prince
https://creativecommons.org/weblog/entry/46087/

hague declaration and limitations and exceptions in relation to tdm
https://creativecommons.org/weblog/entry/45456/

**Comment by peterspdx** [comment]
We've done a lot more in the past on fair use, including commissioning this study in 2009 by the Samuelson Clinic.

https://wiki.creativecommons.org/wiki/Fair_use_study

As discussed, let's be sure any publication we make about fair use ties into the larger policy and legislative pictures at a global level.

Also, suggest we coordinate any fair use post with CC US -- one thought is they could write up a very US-focused picture of fair use, and CC HQ could tie that into a more globally-focused view of CELs.

If we write on fair use, SHP is your point person for legal.

**Comment by tvol** [comment]
https://docs.google.com/document/d/11KwL0q9aV0ZAZTmratdNL1xXYLEZN6H5a6D9ZAh9DXk/edit

**Comment by tvol** [comment]
for communia http://www.communia-association.org/?p=1979&preview=true

**Comment by tvol** [comment]
for CC https://docs.google.com/document/d/11KwL0q9aV0ZAZTmratdNL1xXYLEZN6H5a6D9ZAh9DXk/edit @ericsteuer reviewing (thanks!)

**Comment by tvol** [comment]
https://blog.creativecommons.org/2016/02/23/the-flip-side-of-copyright/
https://twitter.com/creativecommons/status/702242426509856769
