### ISSUE TITLE
draft updated TPP blog post for cc.org

### ISSUE THREAD

**Issue by tvol** [creativecommons/voice-in-copyright-policy#61]
will get @ericsteuer to review draft

**Comment by tvol** [comment]
https://docs.google.com/document/d/1Hz6ti0THfTXRrlhCJBYR3CGI8KgZv7GDbAhmf9NEamk/edit will publish feb 12 am pacific

**Comment by pgstacey** [comment]
Tim:

Thanks for initiating action around this.
In Canada Open Media is leading a opposition to TPP.
I think it may be worth noting as they have done that signing the TPP
agreement is different from ratifying it and getting it approved.
I'd like to see some kind of SOPA like coalition of opposition form around
TPP ratification that involves multiple sister organizations joining forces
in some kind of action of opposition to TPP.
Can we work toward that and call for that in our blog post?

Paul

On Thu, Feb 11, 2016 at 3:43 PM, Timothy Vollmer notifications@github.com
wrote:

> https://docs.google.com/document/d/1Hz6ti0THfTXRrlhCJBYR3CGI8KgZv7GDbAhmf9NEamk/edit
> will publish feb 12 am pacific
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/voice-in-copyright-policy/issues/61#issuecomment-183111468
> .

## 

Paul Stacey
Associate Director of Global Learning
Vancouver, Canada
http://creativecommons.org/staff#paulstacey

**Comment by tvol** [comment]
@pgstacey thanks, yes i will clarify that signing doesn't equal enactment. i wasn't clear enough about that. and I will try to work something in around orgs joining forces. i think this has been happening somewhat already (such as our joint letters and declarations), but not to the level of coordinated actions like SOPA.

**Comment by tvol** [comment]
FYI https://blog.creativecommons.org/2016/02/12/theres-still-time-to-stop-the-tpp/
