### ISSUE TITLE
claudio TPP blog post on cc.org Feb 22

### ISSUE THREAD

**Issue by tvol** [creativecommons/voice-in-copyright-policy#64]

**Comment by tvol** [comment]
@claudioruiz still on for this week?

**Comment by claudiorrrr** [comment]
Yep, but late this week. Is that possible?

**Comment by tvol** [comment]
@claudioruiz yes i think that would be fine. thanks!

**Comment by mattl** [comment]
@tvol -- you should be able to set the post author to Claudio now.

**Comment by tvol** [comment]
@claudioruiz are you planning on writing this still?
