### ISSUE TITLE
brainstorm policy interview ideas w/eric

### ISSUE THREAD

**Issue by tvol** [creativecommons/voice-in-copyright-policy#70]

**Comment by tvol** [comment]
https://docs.google.com/document/d/1tngIV1_sdtSIOsL8AQ-2Cb4baGmr2ZkyF07IZUasrco/edit

**Comment by pgstacey** [comment]
Tim, need permission to view.
Paul

On Tue, Mar 29, 2016 at 3:18 PM, Timothy Vollmer notifications@github.com
wrote:

> https://docs.google.com/document/d/1tngIV1_sdtSIOsL8AQ-2Cb4baGmr2ZkyF07IZUasrco/edit
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/voice-in-copyright-policy/issues/70#issuecomment-203136577

## 

Paul Stacey
Associate Director of Global Learning
Vancouver, Canada

We're hiring! Help us make the Commons more discoverable, usable, and
connected. Opportunities in tech, communications, and fundraising:
http://bit.ly/1OZ46OF

**Comment by tvol** [comment]
done
