### ISSUE TITLE
blog post re: link tax and freedom panorama

### ISSUE THREAD

**Issue by tvol** [creativecommons/voice-in-copyright-policy#91]
Hi @little-wow, @ericsteuer can one of you please review this blog post draft? would like to get it up by COB today. thanks
https://docs.google.com/document/d/14TVJjda5vcOUmLDjdZH5lCyfefjQ3jsFzbmBjZJsbjs/edit

**Comment by ericsteuer** [comment]
i'll take a pass now.

still getting the hang of github. is there a way for me to "un-assign" @little-wow so it's off her plate?

**Comment by little-wow** [comment]
There you go :)

**Comment by ericsteuer** [comment]
#learning

thanks @little-wow

**Comment by ericsteuer** [comment]
Hey @tvol, I've added some comments/thoughts to the gdoc.

**Comment by tvol** [comment]
@ericsteuer thanks. fyi https://blog.creativecommons.org/2016/06/13/tell-european-commission-fixcopyright/
