### ISSUE TITLE
draft education policy brief with Commonwealth

### ISSUE THREAD

**Issue by tvol** [creativecommons/voice-in-copyright-policy#96]
https://docs.google.com/document/d/1Nto3Rc_Y25x2Hh1OrNoJwqPuWwG9jXAVrqJn5XOqsXg/edit

**Comment by tvol** [comment]
@cablegreen I started to sketch out an outline. Can you take a look at bullets 1-4 in this doc?

**Comment by cablegreen** [comment]
Thanks Tim. Great start. I like the outline. I made some edits / additions.  I intend to work on it more next week. In Houston today/tomorrow.

**Comment by tvol** [comment]
done
